export const Phase = {
  LOBBY: 'LOBBY',
  ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT',
  SHOWING_ROLES: 'SHOWING_ROLES',
  QUESTIONING: 'QUESTIONING',
  REVEAL_GUESS: 'REVEAL_GUESS',
  CRAZY_PATIENT_GUESS: 'CRAZY_PATIENT_GUESS',
  RESULTS: 'RESULTS',
  END_GAME: 'END_GAME',
};
